# Generated by Django 3.1.4 on 2021-11-16 21:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211116_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('messages', tinymce.models.HTMLField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
