# Generated by Django 3.1.4 on 2021-11-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211116_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='csno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
