# Generated by Django 3.1.4 on 2021-11-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211116_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='csno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
